container:
  image: quay.io/tarilabs/rust:1.30-alpine
  additional_containers:
  - name: postgres
    image: postgres:9.6
    port: 5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

test_task:
  target_cache:
    folder: target
    fingerprint_script: cat Cargo.lock
    populate_script: cargo install
  script: ./scripts/run-other-tests.sh
