---
kind: pipeline
name: bn-api

pipeline:
    restore-cache:
      image: plugins/s3-cache
      pull: true
      restore: true
      endpoint:
          from_secret: aws_s3_endpoint
      access_key:
          from_secret: aws_access_key_id
      secret_key:
          from_secret: aws_secret_access_key
      mount:
          - ./target
      root:
          from_secret: aws_s3_bucket

      test1:
      depends_on: ["restore-cache"]
      image: rust:1.31.1
      environment:
          - FRONT_END_URL="http://localhost"
          - BIGNEON_DB=bigneon
          - DATABASE_URL=postgres://app:password@database/bigneon_test
          - TEST_DATABASE_URL=postgres://app:password@database/bigneon_test
          - TEST_DATABASE_ADMIN_URL=postgres://app:password@database/bigneon_test
          - BUILD_DIR="api"
          - TARI_URL="TEST"
          - COMMUNICATION_DEFAULT_SOURCE_EMAIL="noreply@bigneon.com"
          - COMMUNICATION_DEFAULT_SOURCE_PHONE="0112223333"
          - TOKEN_SECRET=travis_secret
          - TOKEN_ISSUER=bg-on-travis
          - STRIPE_SECRET_KEY="sk_test_iGn9c6EJyuF3Gx0QH6uitQlb"
          - SENDGRID_API_KEY=" "
          - SENDGRID_TEMPLATE_BN_REFUND="d-9ba23272db854578a5609e4e4c608f9f"
          - SENDGRID_TEMPLATE_BN_USER_REGISTERED="d-9ba23272db854578a5609e4e4c608f9f"
          - SENDGRID_TEMPLATE_BN_PURCHASE_COMPLETED="d-c23ba549dd0749bbb3b244b758c05dd7"
          - SENDGRID_TEMPLATE_BN_ORG_INVITE="d-19ea07c6169e4fe887b6527ef16cb1ea"
          - SENDGRID_TEMPLATE_BN_TRANSFER_TICKETS="d-f6a449f0281e404899eb4d580bc342a3"
          - SENDGRID_TEMPLATE_BN_PASSWORD_RESET="d-193ea5665fc54c8ca19c6325c8e46703"
          - SENDGRID_TEMPLATE_BN_USER_INVITE="d-fcf7791b781644a8960820058c9074fd"
          - GH_USER_EMAIL='sdbondi@users.noreply.github.com'
          - GH_USER_NAME='Travis CI'
          - HTTP_KEEP_ALIVE=75
          - BLOCK_EXTERNAL_COMMS=1
          - TWILIO_ACCOUNT_ID=" "
          - TWILIO_API_KEY=" "
          - API_KEYS_ENCRYPTION_KEY="test_key"
          - GLOBEE_API_KEY="GDFOzMkPAw79a8TCAHKkiknJB6bEYgbb"
          - GLOBEE_BASE_URL="https://test.globee.com/payment-api/v1/"
          - IPN_BASE_URL="TEST"
      commands:
  #            - rustup component add rustfmt-preview
  #            - cargo fmt --all -- --check
          - ./scripts/run-other-tests.sh

#    test2:
#        depends_on: ["restore-cache"]
#        image: rust:1.31.1
#        environment:
#            - FRONT_END_URL="http://localhost"
#            - BIGNEON_DB=bigneon
#            - TEST_DATABASE_URL=postgres://app:password@database/bigneon_test
#            - TEST_DATABASE_ADMIN_URL=postgres://app:password@database/bigneon_test
#            - BUILD_DIR="api"
#            - TARI_URL="TEST"
#            - COMMUNICATION_DEFAULT_SOURCE_EMAIL="noreply@bigneon.com"
#            - COMMUNICATION_DEFAULT_SOURCE_PHONE="0112223333"
#            - TOKEN_SECRET=travis_secret
#            - TOKEN_ISSUER=bg-on-travis
#            - STRIPE_SECRET_KEY="sk_test_iGn9c6EJyuF3Gx0QH6uitQlb"
#            - SENDGRID_API_KEY=" "
#            - SENDGRID_TEMPLATE_BN_REFUND="d-9ba23272db854578a5609e4e4c608f9f"
#            - SENDGRID_TEMPLATE_BN_USER_REGISTERED="d-9ba23272db854578a5609e4e4c608f9f"
#            - SENDGRID_TEMPLATE_BN_PURCHASE_COMPLETED="d-c23ba549dd0749bbb3b244b758c05dd7"
#            - SENDGRID_TEMPLATE_BN_ORG_INVITE="d-19ea07c6169e4fe887b6527ef16cb1ea"
#            - SENDGRID_TEMPLATE_BN_TRANSFER_TICKETS="d-f6a449f0281e404899eb4d580bc342a3"
#            - SENDGRID_TEMPLATE_BN_PASSWORD_RESET="d-193ea5665fc54c8ca19c6325c8e46703"
#            - SENDGRID_TEMPLATE_BN_USER_INVITE="d-fcf7791b781644a8960820058c9074fd"
#            - GH_USER_EMAIL='sdbondi@users.noreply.github.com'
#            - GH_USER_NAME='Travis CI'
#            - HTTP_KEEP_ALIVE=75
#            - BLOCK_EXTERNAL_COMMS=1
#            - TWILIO_ACCOUNT_ID=" "
#            - TWILIO_API_KEY=" "
#            - API_KEYS_ENCRYPTION_KEY="test_key"
#            - GLOBEE_API_KEY="GDFOzMkPAw79a8TCAHKkiknJB6bEYgbb"
#            - GLOBEE_BASE_URL="https://test.globee.com/payment-api/v1/"
#            - IPN_BASE_URL="TEST"
#        commands:
#            - ./scripts/run-api-tests.sh

    rebuild-cache:
        image: plugins/s3-cache
        pull: true
        rebuild: true
        endpoint:
            from_secret: aws_s3_endpoint
        access_key:
            from_secret: aws_access_key_id
        secret_key:
            from_secret: aws_secret_access_key
        mount:
            - ./target
        root:
            from_secret: aws_s3_bucket

services:
    database:
      image: postgres:10.4
      environment:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bigneon_test
