pipeline:
  test1:
      group: test
      image: quay.io/tarilabs/rust:1.30
      commands:
      - ./scripts/run-other-tests.sh


    test2:
      group: test
      image: quay.io/tarilabs/rust:1.30
      commands:
      - ./scripts/run-other-tests.sh

