kind: pipeline
name: bn-api

pipeline:
  test1:
      group: test
      image: rust:1.31.1
      environment:
          - TEST_DATABASE_URL=postgres://database:5432/test1
          - DATABASE_URL=postgres://database:5432/test1
      commands:
      - ./scripts/run-other-tests.sh


  test2:
      group: test
      image: rust:1.31.1
      environment:
          - TEST_DATABASE_URL=postgres://database:5432/test2
          - DATABASE_URL=postgres://database:5432/test2
      commands:
          - ./scripts/run-api-tests.sh

services:
    database:
        image: postgres

