
kind: pipeline
name: Tests

steps:
    - name: restore-cache
      depends_on: ["clone"]
      image: plugins/s3-cache
      settings:
        restore: true
        endpoint: http://minio1:9000
        access_key:
            from_secret: access_key_id
        secret_key:
            from_secret: secret_access_key
        mount:
            - ./target
        fallback_path: drone/$DRONE_REPO_NAMESPACE/$DRONE_REPO_NAME/master/
        root: drone


when:
    event: [pull_request]

services:
    - name: database
      image: postgres:10.4
      environment:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password

