kind: pipeline
name: bn-api

pipeline:
    restore-cache:
	image: plugins/s3-cache
	pull: true
	restore: true
	endpoint:
	    from_secret: aws_s3_endpoint
	access_key:
	    from_secret: aws_access_key_id
	secret_key:
	    from_secret: aws_secret_access_key
	mount:
	    - ./target
	root:
	    from_secret: aws_s3_bucket

    test1:
	group: test
	image: rust:1.31.1
	environment:
	    - TEST_DATABASE_URL=postgres://app:password@database:5432/test1
	    - DATABASE_URL=postgres://app:password@database:5432/test1
	commands:
	    - ./scripts/run-other-tests.sh

    test2:
	group: test
	image: rust:1.31.1
	environment:
	    - TEST_DATABASE_URL=postgres://app:password@database:5432/test2
	    - DATABASE_URL=postgres://app:password@database:5432/test2
	commands:
	    - ./scripts/run-api-tests.sh

    rebuild-cache:
	image: plugins/s3-cache
	pull: true
	rebuild: true
	endpoint:
	    from_secret: aws_s3_endpoint
	access_key:
	    from_secret: aws_access_key_id
	secret_key:
	    from_secret: aws_secret_access_key
	mount:
	    - ./target
	root:
	    from_secret: aws_s3_bucket

services:
    database:
	image: postgres:10.4
	environment:
	    POSTGRES_USER: app
	    POSTGRES_PASSWORD: password

