kind: pipeline
name: bn-api

pipeline:
    restore-cache:
        image: drillster/drone-volume-cache
        restore: true
        mount:
            - ./target
        # Mount the cache volume, needs "Trusted"
        volumes:
            - /tmp/cache/bn-api:/cache

    test1:
        group: test
        image: rust:1.31.1
        environment:
            - TEST_DATABASE_URL=postgres://app:password@database:5432/test1
            - DATABASE_URL=postgres://app:password@database:5432/test1
        commands:
            - ./scripts/run-other-tests.sh

     test2:
         group: test
         image: rust:1.31.1
         environment:
             - TEST_DATABASE_URL=postgres://app:password@database:5432/test2
             - DATABASE_URL=postgres://app:password@database:5432/test2
         commands:
             - ./scripts/run-api-tests.sh

    restore-cache:
        image: drillster/drone-volume-cache
        rebuild: true
        mount:
          - ./target
        # Mount the cache volume, needs "Trusted"
        volumes:
          - /tmp/cache/bn-api:/cache

services:
    database:
        image: postgres:10.4
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: password

