language: rust
rust:
- stable
cache: cargo
services:
- postgresql
addons:
  postgresql: '9.6'
branches:
  only:
  - master
matrix:
  include:
  - stage: tests
    name: Test API
    env:
    - TEST_SCRIPT="run-api-tests.sh"
    - DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
  - stage: tests
    name: Test Other
    env:
    - TEST_SCRIPT="run-other-tests.sh"
    - DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
  - stage: tests
    name: Test Postman
    env:
    - TEST_SCRIPT="run-integration-tests.sh"
    - DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
    - RUST_BACKTRACE=1
    - RUST_LOG=error # Postman output is very verbose
  - stage: tests
    name: Cargo Audit
    env:
    - TEST_SCRIPT="run-cargo-audit.sh"
    - DATABASE_URL=NA
  - stage: deploy
    script: skip
    deploy:
      provider: script
      script: bash scripts/travis_tag.sh
      on:
        branch: master
  fast_finish: true
script:
- "./scripts/$TEST_SCRIPT"
before_install:
- export PATH="$PATH:$HOME/.cargo/bin"
- rustup component add rustfmt-preview
- cargo fmt --all -- --check
before_script: []
after_script: []
env:
  global:
  - FRONT_END_URL="http://localhost"
  - BIGNEON_DB=bigneon
  - TEST_DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
  - TEST_DATABASE_ADMIN_URL=postgres://postgres:password123@localhost/bigneon_test
  - BUILD_DIR="api"
  - TARI_URL="TEST"
  - COMMUNICATION_DEFAULT_SOURCE_EMAIL="noreply@bigneon.com"
  - COMMUNICATION_DEFAULT_SOURCE_PHONE="0112223333"
  - TOKEN_SECRET=travis_secret
  - TOKEN_ISSUER=bg-on-travis
  - STRIPE_SECRET_KEY="sk_test_iGn9c6EJyuF3Gx0QH6uitQlb"
  - SENDGRID_API_KEY=" "
  - SENDGRID_TEMPLATE_BN_REFUND="d-9ba23272db854578a5609e4e4c608f9f"
  - SENDGRID_TEMPLATE_BN_USER_REGISTERED="d-9ba23272db854578a5609e4e4c608f9f"
  - SENDGRID_TEMPLATE_BN_PURCHASE_COMPLETED="d-c23ba549dd0749bbb3b244b758c05dd7"
  - SENDGRID_TEMPLATE_BN_ORG_INVITE="d-19ea07c6169e4fe887b6527ef16cb1ea"
  - SENDGRID_TEMPLATE_BN_TRANSFER_TICKETS="d-f6a449f0281e404899eb4d580bc342a3"
  - SENDGRID_TEMPLATE_BN_PASSWORD_RESET="d-193ea5665fc54c8ca19c6325c8e46703"
  - SENDGRID_TEMPLATE_BN_USER_INVITE="d-fcf7791b781644a8960820058c9074fd"
  - GH_USER_EMAIL='sdbondi@users.noreply.github.com'
  - GH_USER_NAME='Travis CI'
  - HTTP_KEEP_ALIVE=75
  - BLOCK_EXTERNAL_COMMS=1
  - TWILIO_ACCOUNT_ID=" "
  - TWILIO_API_KEY=" "
  - API_KEYS_ENCRYPTION_KEY="test_key"
  - GLOBEE_API_KEY="GDFOzMkPAw79a8TCAHKkiknJB6bEYgbb"
  - GLOBEE_BASE_URL="https://test.globee.com/payment-api/v1/"
  - IPN_BASE_URL="http://localhost"
