[package]
name = "bigneon_http"
version = "0.1.0"
authors = ["Stan <sdbondi@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"

[dev-dependencies]
bigneon_caching_derive = { path = "caching_derive" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
